#!/usr/bin/env php
<?php

// Check if Composer global require or project directory
if (file_exists($composerAutoload = __DIR__.'/../../autoload.php')) {
    require_once $composerAutoload;
} else {
    require_once __DIR__.'/vendor/autoload.php';
}

use JFastnacht\DiceRoller\Command\RollCommand as RollCommandAlias;
use JFastnacht\DiceRoller\Command\SelfcheckCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new RollCommandAlias());
$application->add(new SelfcheckCommand());

try {
    $application->run();
} catch (Exception $e) {
    echo $e->getMessage();
}
